---
  name: Build and Push Image to Google Cloud Platform
  on:
    push:
      branches: [ main ]
  jobs:
    build-push-gcr:
      name: Build and Push to GCP
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: first try image
        PROJECT_ID: smenjivar-dev
      steps:
      - name: Checkout
        uses: 'actions/checkout@v4'
  
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Docker version and Buildx information
        run: |
          docker version
          docker buildx version
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0  # Use the latest version
      - name: Print Docker version
        run: docker version
      
      - name: Build and push Docker image
        run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64 -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest .
  
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major
  
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
  
      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  
      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG